server:
  port: 8099 

spring:
  application:
    name: cloud-gateway
    

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: 163_route
          uri: http://www.163.com/
          predicates:
          - Path=/163
        - id: consul-oauth
          uri: lb://cloud-auth/oauth/**
          predicates:
          - Path=/oauth/**
          filters:           
           - name: Hystrix
             args:
               name: fallbackcmd
               fallbackUri: forward:/hystrixTimeout
               
        - id: consul-anth
          uri: lb://cloud-auth/user/**
          predicates:
          - Path=/user/**
          filters:           
           - name: Hystrix
             args:
               name: fallbackcmd
               fallbackUri: forward:/hystrixTimeout               
               
        - id: consul-anth
          uri: lb://cloud-auth/menu/**
          predicates:
          - Path=/menu/**
          filters:           
           - name: Hystrix
             args:
               name: fallbackcmd
               fallbackUri: forward:/hystrixTimeout    
               
        - id: consul-file
          uri: lb://cloud-service/file/**
          predicates:
          - Path=/file/**
          filters:           
           - name: Hystrix
             args:
               name: fallbackcmd
               fallbackUri: forward:/hystrixTimeout                    
                                              
               
    consul:
      enabled: true
      host: localhost
      port: 8500
      discovery:
        service-name: cloud-gateway
        register: true