server:
  port: 8011

spring:
  application:
    name: cloud-auth
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/cloud_database?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF-8
     username: root
     password: 123456
     driverClassName: com.mysql.jdbc.Driver

  cloud: 
    consul:
      enabled: true
      host: localhost
      port: 8500
      discovery:
        service-name: cloud-auth
        register: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  security: 
    oauth2: 
      resource: 
        filter-order: 3      
      
mybatis:
  configuration: 
    map-underscore-to-camel-case: true